export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ADD = 'ADD'
export const SUBTRACT = 'SUBTRACT'
export const RESET = 'RESET'
export const SAVE = 'SAVE'
export const REMOVE = 'REMOVE'